version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      aws:
        applies-to: version-updates
        patterns:
        - "github.com/aws/aws-sdk-go-v2*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: "main"
