name: deploy site
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    name: deploy
    permissions:
      contents: write
      pages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.114.1"
          extended: true

      - name: build
        run: |
          cd site
          hugo --minify

      - name: deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public
