name: run-app
on:
  schedule:
    - cron: "0 1 * * *" # run at 1 AM UTC on weekdays
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    name: send status update
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: run app
        run: go run .
        env:
          MASTODON_SERVER: ${{ secrets.MASTODON_SERVER }}
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_SECRET_KEY: ${{ secrets.MASTODON_SECRET_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
          X_REFRESH_TOKEN: ${{ secrets.X_REFRESH_TOKEN }}
      - name: commit
        run: |
          git config --global user.email "gh-actions"
          git config --global user.name "gh-actions"
          git checkout -b store-changes
          git commit -a -m "Store changes to data."
          git push --set-upstream origin store-changes
          url=$(gh pr create --fill)
          gh pr merge --auto --merge "$url"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
