name: run-app
on:
  schedule:
    - cron: "0 3 * * *" # run at 3 AM UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    name: send status update
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASER_APP_ID }}
          private-key: ${{ secrets.RELEASER_APP_KEY }}
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: setup
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: run app
        run: |
          go run .
          source ./data/.envrc
          gh secret set X_REFRESH_TOKEN --body "$NEW_X_REFRESH_TOKEN"
        env:
          CLOUD_BUCKET_URL: ${{ secrets.CLOUD_BUCKET_URL }}
          CLOUD_BUCKET_NAME: ${{ secrets.CLOUD_BUCKET_NAME }}
          CLOUD_ACCOUNT_ID: ${{ secrets.CLOUD_ACCOUNT_ID }}
          CLOUD_ACCESS_KEY_ID: ${{ secrets.CLOUD_ACCESS_KEY_ID }}
          CLOUD_ACCESS_KEY_SECRET: ${{ secrets.CLOUD_ACCESS_KEY_SECRET }}
          MASTODON_SERVER: ${{ secrets.MASTODON_SERVER }}
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_SECRET_KEY: ${{ secrets.MASTODON_SECRET_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
          X_REFRESH_TOKEN: ${{ secrets.X_REFRESH_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_PAGE_TOKEN: ${{ secrets.FACEBOOK_PAGE_TOKEN }}
          INSTAGRAM_BUSINESS_ACCOUNT: ${{ secrets.INSTAGRAM_BUSINESS_ACCOUNT }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: commit
        run: |
          git config --global user.email "gh-actions"
          git config --global user.name "gh-actions"
          branch="store-changes-$(date +%s)"
          git checkout -b $branch
          git add site
          git commit -a -m "Store changes to data."
          git push --set-upstream origin $branch
          url=$(gh pr create --fill)
          gh pr merge --auto --merge "$url"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
