name: run-app
on:
  schedule:
    - cron: "0 1 * * *" # run at 1 AM UTC on weekdays
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    name: send status update
    permissions:
      contents: write
      pull-requests: write
      pages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.PAT}}
      - name: setup
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: run app
        run: |
          go run .
          source ./data/.envrc
          gh secret set X_REFRESH_TOKEN --body "$NEW_X_REFRESH_TOKEN"
        env:
          MASTODON_SERVER: ${{ secrets.MASTODON_SERVER }}
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_SECRET_KEY: ${{ secrets.MASTODON_SECRET_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
          X_REFRESH_TOKEN: ${{ secrets.X_REFRESH_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_PAGE_TOKEN: ${{ secrets.FACEBOOK_PAGE_TOKEN }}
          GH_TOKEN: ${{secrets.PAT}}
      - name: commit
        run: |
          git config --global user.email "gh-actions"
          git config --global user.name "gh-actions"
          branch="store-changes-$(date +%s)"
          git checkout -b $branch
          git add site
          git commit -a -m "Store changes to data."
          git push --set-upstream origin $branch
          url=$(gh pr create --fill)
          gh pr merge --auto --merge "$url"
        env:
          GH_TOKEN: ${{secrets.PAT}}

      # update site
      - uses: ./.github/actions/deploy-site
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.114.1"
          extended: true

      - name: build
        run: |
          cd site
          hugo --minify

      - name: deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public
